{% set version = '2.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-wordcloud
  version: {{ version|replace("-", "_") }}

source:
  fn: wordcloud_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/wordcloud_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/wordcloud/wordcloud_{{ version }}.tar.gz
  sha256: 95e173192daa90065ffe617094528b5c0bf7fbd9a8fd40da68910788ea6c58aa

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-rcpp
    - r-slam

  run:
    - r-base
    - r-rcolorbrewer
    - r-rcpp
    - r-slam

test:
  commands:
    - $R -e "library('wordcloud')"  # [not win]
    - "\"%R%\" -e \"library('wordcloud')\""  # [win]

about:
  home: http://blog.fellstat.com/?cat=11, http://www.fellstat.com
  license: LGPL-2.1
  summary: Pretty word clouds.
  license_family: LGPL

extra:
  recipe-maintainers:
    - dpryan79
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
