appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: InQYOQ8hdyhE5e8GG5MoMkToax7yuK+h8lffwEY3+5J6jhpkCAqVvSJ28Kaas/zotrOTE3EJXv+5r70iTv8+A2xi+i7l/gyffYWr+WpADMSZeEsXXRGAlMBtV1q44hfQvY+yT5ExDLM9BQ658k8H+EEsU2Y2/NdR6srDT3KR8PvUqv0n0nvsl/mG68uXdrH3MzvSiFtUJwrHlAxoWOPjq+lMEqa6XWnkZ38IxCm8XWd0bbp+BAmaqJe9LBjHK9AksrsYczSU+OGjjCXRXF/DghQqrhGbSfRqIhkwni/iOZus+J7Ciep10ZTMd9ADpG3LDE3JKjWtH6eW7sDnnLKRTZiFqR2IRvmB2bPhklnOAPYlJtxUjyZYwkOqgE65VBStGXVmawiKRhPbK11n1FG9SXMu62Sqig1jqaaW4gT2dalJWS4nMjylL8y+Unzs7AiuAelPMsszFlbfDgmpLcJU+erfXPWaicGMBy2Ec88TLQM0xQ/IHmq0VXkaxdkM14730TE+Z8oIaRJYsbt6n5HgTitzT33NJ4aGazQsbbiYzspnRqYVYL0Q6P/X+Y0owdaDENpOsmdIbaFvcTXMUBkUWESivIKKS6L/jbvEMdxEuTOu7dVJcn7Hcs6sBp2Q7edIijKYViZaCn+FU33NWotxXkaoe+JC7hKKnWyR3akPDkg=
